name: cs1671-project
channels:
  - defaults
dependencies:
  - aiodns=3.5.0=py313haa95532_1
  - aiohappyeyeballs=2.6.1=py313haa95532_0
  - aiohttp=3.13.3=py313h02ab6af_0
  - aiosignal=1.4.0=py313haa95532_0
  - anyio=4.10.0=py313haa95532_0
  - arrow=1.4.0=py313haa95532_0
  - arrow-cpp=23.0.1=hda990a8_0
  - attrs=25.4.0=py313haa95532_2
  - aws-c-auth=0.9.4=h02ab6af_0
  - aws-c-cal=0.9.13=h630b2a1_0
  - aws-c-common=0.12.6=h02ab6af_0
  - aws-c-compression=0.3.1=h02ab6af_3
  - aws-c-event-stream=0.5.9=h02ab6af_0
  - aws-c-http=0.10.7=h02ab6af_0
  - aws-c-io=0.23.3=h02ab6af_0
  - aws-c-mqtt=0.13.3=h02ab6af_1
  - aws-c-s3=0.11.3=h02ab6af_0
  - aws-c-sdkutils=0.2.4=h02ab6af_2
  - aws-checksums=0.2.8=h02ab6af_0
  - aws-crt-cpp=0.35.4=h885b0b7_0
  - aws-sdk-cpp=1.11.720=hf0af688_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - blas=1.0=mkl
  - bottleneck=1.4.2=py313h540bb41_1
  - brotlicffi=1.2.0.0=py313h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.6=h2c209ce_0
  - ca-certificates=2025.12.2=haa95532_0
  - certifi=2026.01.04=py313haa95532_0
  - cffi=2.0.0=py313h02ab6af_1
  - chardet=5.2.0=py313haa95532_0
  - charset-normalizer=3.4.4=py313haa95532_0
  - click=8.2.1=py313haa95532_1
  - colorama=0.4.6=py313haa95532_0
  - cookiecutter=2.6.0=py313haa95532_1
  - datasets=4.4.1=py313haa95532_1
  - dill=0.4.0=py313haa95532_0
  - evaluate=0.4.6=py313h51baaa3_0
  - filelock=3.20.3=py313haa95532_0
  - frozenlist=1.8.0=py313h885b0b7_0
  - fsspec=2025.10.0=py313h4442805_0
  - gflags=2.2.2=hd77b12b_1
  - glog=0.5.0=hd77b12b_1
  - h11=0.16.0=py313haa95532_1
  - hf-xet=1.2.0=py313h17722a0_0
  - httpcore=1.0.9=py313haa95532_0
  - httpx=0.28.1=py313haa95532_1
  - huggingface_hub=1.3.3=py313h4442805_0
  - idna=3.11=py313haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - jinja2=3.1.6=py313haa95532_0
  - joblib=1.5.3=py313haa95532_0
  - libabseil=20260107.0=cxx17_hc587421_0
  - libbrotlicommon=1.2.0=h907acca_0
  - libbrotlidec=1.2.0=h02c67a5_0
  - libbrotlienc=1.2.0=h483e6b9_0
  - libcurl=8.18.0=he215731_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libgrpc=1.78.0=hecd3d80_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.18=hc89ec93_0
  - libkrb5=1.22.1=hb237eb7_0
  - libmpdec=4.0.0=h827c3e9_0
  - libprotobuf=6.33.5=h65d7223_0
  - libre2-11=2025.11.05=h797e85b_1
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.22.0=ha2884a9_0
  - libuv=1.48.0=h827c3e9_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markdown-it-py=4.0.0=py313haa95532_1
  - markupsafe=3.0.2=py313h827c3e9_0
  - mdurl=0.1.2=py313haa95532_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py313h0b37514_0
  - mkl_fft=2.1.1=py313hbc2a22c_0
  - mkl_random=1.3.0=py313h42c1672_0
  - multidict=6.7.1=py313h1c6eee0_0
  - multiprocess=0.70.18=py313haa95532_1
  - nltk=3.9.2=py313h63c8d5c_0
  - numexpr=2.14.1=py313h7660c64_0
  - numpy=2.4.2=py313h22cce72_0
  - numpy-base=2.4.2=py313h1df51cf_0
  - openssl=3.0.19=hbb43b14_0
  - orc=2.2.0=h1e45922_2
  - packaging=25.0=py313haa95532_1
  - pandas=2.3.3=py313h42c1672_1
  - pip=26.0.1=pyhc872135_0
  - propcache=0.4.1=py313h02ab6af_0
  - pyarrow=23.0.1=py313hf6ff4c0_0
  - pycares=4.10.0=py313he29e43d_0
  - pycparser=2.23=py313haa95532_0
  - pygments=2.19.2=py313haa95532_0
  - pysocks=1.7.1=py313haa95532_1
  - python=3.13.12=h39c999c_100_cp313
  - python-dateutil=2.9.0post0=py313haa95532_2
  - python-slugify=8.0.4=py313haa95532_0
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py313h827c3e9_0
  - python_abi=3.13=3_cp313
  - pytz=2025.2=py313haa95532_0
  - pyyaml=6.0.3=py313hb9a58be_0
  - re2=2025.11.05=hca2749c_1
  - regex=2025.11.3=py313h02ab6af_0
  - requests=2.32.5=py313haa95532_1
  - rich=14.2.0=py313haa95532_0
  - setuptools=80.10.2=py313haa95532_0
  - shellingham=1.5.4=py313haa95532_0
  - six=1.17.0=py313haa95532_0
  - snappy=1.2.2=hab6b7b3_1
  - sniffio=1.3.1=py313haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - tk=8.6.15=hf199647_0
  - tqdm=4.67.3=py313h4442805_1
  - typer-slim=0.20.0=py313haa95532_1
  - typing-extensions=4.15.0=py313haa95532_0
  - typing_extensions=4.15.0=py313haa95532_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.3=py313haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py313haa95532_0
  - win_inet_pton=1.1.0=py313haa95532_1
  - winloop=0.3.1=py313h913537a_0
  - xxhash=0.8.0=h2bbff1b_3
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yarl=1.22.0=py313h02ab6af_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
prefix: C:\Users\finnh\anaconda3\envs\cs1671-project
